version: '3'

volumes:
  blogging_platform_local_postgres_data: {}
  blogging_platform_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: blogging_platform_local_django
    container_name: blogging_platform_local_django
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  redis:
    image: redis:6

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: blogging_platform_production_postgres
    container_name: blogging_platform_local_postgres
    volumes:
      - blogging_platform_local_postgres_data:/var/lib/postgresql/data
      - blogging_platform_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: blogging_platform_local_docs
    container_name: blogging_platform_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./blogging_platform:/app/blogging_platform:z
    ports:
      - '9000:9000'
    command: /start-docs
