apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: blogging_platform_production_postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-backups
              mountPath: /backups
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: dbname
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: production-postgres-data
        - name: postgres-backups
          persistentVolumeClaim:
            claimName: production-postgres-data-backups
