apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-django-media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/production_django_media
