apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-postgres-data-backups
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/production_postgres_data_backups
