apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-postgres
  template:
    metadata:
      labels:
        app: local-postgres
    spec:
      containers:
        - name: local-postgres
          image: blogging_platform_production_postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-backups
              mountPath: /backups
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: dbname
            # Add other environment variables as needed
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-backups
          emptyDir: {}
